### ISSUE TITLE
Lexer nm610 ssd wont be detected[only endavour artemis_22_6]

### ISSUE THREAD

**Issue by mr-nemesis** [endeavouros-team/EndeavourOS-ISO#31]
**[this issue seems to be only with endavour os, tried arch, artix , pop os , debian so far]** I have 2 ssds in my pc, i tried to install endavour os artemis on my system, but it wont pick up my lexar ssd no matter what, swapped the ssd position, it wont detect that, all other distros do detect and work fine with it, the bug seems to be with the lattest endavour os iso, previous ones do detect and work normally with the ssd, it is probably **lexar nm610,** please fix the bug

**Comment by killajoe** [comment]
https://forum.endeavouros.com/t/lexer-nm610-ssd-wont-be-detected-only-endavour-artemis-22-6/29059
closing
