### ISSUE TITLE
calamares: error while loading shared libraries: libboost_python310.so.1.79.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by gnuhub** [endeavouros-team/EndeavourOS-ISO#32]
```
extra/boost-libs 1.80.0-1
but the endeavouros/calamares_current 22.09.2.3-1
    Calamares installer for EndeavourOS
links to libboost_python310.so.1.79.0
```
the iso build  can not install now

**Comment by killajoe** [comment]
You need to rebuild calamares package or symlink the lib.
And this is not an issue with the ISO its the calamares package build for current release. 
We do use git package locally builds on the latest development. 

https://github.com/endeavouros-team/EndeavourOS-ISO#advanced
https://github.com/endeavouros-team/PKGBUILDS/tree/master/calamares-git

**Comment by killajoe** [comment]
but i decided to update calamares_current on repo.. we will need it too if we want to release updated ISO in case:
https://github.com/endeavouros-team/PKGBUILDS/commit/992bd8156bb2e22361c0475f534d305bcbc662df

will need some time to get into repos..
