### ISSUE TITLE
development branch git master-build the iso is different ,no theme

### ISSUE THREAD

**Issue by gnuhub** [endeavouros-team/EndeavourOS-ISO#33]
# 1 build the iso
```
git clone https://github.com/endeavouros-team/EndeavourOS-ISO.git
cd "EndeavourOS-ISO"
./prepare.sh

sudo ./mkarchiso -v "."

```
# 2 install the build iso offline install

![eos](https://user-images.githubusercontent.com/1329093/191390796-8369a787-6089-43af-88f8-b0bf0fd18e12.png)

# 3 question : why it is different ,no theme?

**Comment by killajoe** [comment]
solved by what? ;)
Will be something went wrong on prepare or after it.. like it does not reinstall endeavouros-skel-xfce4 ? the install log would show
