### ISSUE TITLE
Support for grub loopback missing

### ISSUE THREAD

**Issue by Mexit** [endeavouros-team/EndeavourOS-ISO#4]
EndeavourOS does not use grub as ISO bootloader. Instead, syslinux and systemd-boot are used.
Grub is becoming more and more popular on ISO images, replacing sysylinux. I think it is worth adding a configuration to allow booting from the image via grub loopback.
This will allow you to run the EndeavourOS ISO image directly from a flash drive or hard drive. No need to burn the ISO to disk, just copy to disk as file and boot from it.
Here a sample grub configuration file for EndeavourOS: https://gist.github.com/Mexit/e6f923f1ff2bfbf835196963cf8873ba

More info:
https://github.com/Mexit/MultiOS-USB
https://osinside.github.io/kiwi/working_with_images/iso_to_usb_stick_grub2_boot_from_iso.html

**Comment by killajoe** [comment]
> No need to burn the ISO to disk, just copy to disk as file and boot from it.

Exactly what Archiso is doing it is a hybrid-iso that can be written to DVD or directly booted from USB stick.

https://gitlab.archlinux.org/archlinux/archiso/-/blob/master/archiso/mkarchiso

**Comment by Mexit** [comment]
Correct, but how many ISO images can you have on one USB drive at a time? 
`One`  

This is neither convenient nor practical.

**Comment by killajoe** [comment]
So partly because i do not fully understand how your code is working.. indeed nice if possible, but we are really short on development time at the moment, and changing the ISO is not planned currently, as we mainly use bare Arch-ISO configured to work for us.  I could think of try that as a project, but this will be more next year I think ;) 
Thanks to clarify!

**Comment by Mexit** [comment]
I understand. Then some information for the future.
All you need to do is add the following kernel parameters to the existing ones:
`img_dev=/dev/disk/by-uuid/${rootuuid} img_loop=${iso_path}`
and save it to `/boot/grub/loopback.cfg` in the ISO image ([example](https://gist.github.com/Mexit/e6f923f1ff2bfbf835196963cf8873ba)).
The above kernel parameters tell the kernel to find and mount an ISO image instead of a CD/DVD.
If necessary, I can help.
