### ISSUE TITLE
build iso using main branch of EndeavourOS-ISO,when installing it,there is an error

### ISSUE THREAD

**Issue by gnuhub** [endeavouros-team/EndeavourOS-ISO#40]
![pic_2022-10-28_08-44-55](https://user-images.githubusercontent.com/1329093/198423476-dc742306-4a1e-4120-be4b-e446d288d4ab.png)

**Comment by killajoe** [comment]
yes as the readme says you will need to use the tag from last release to build release iso, main branch is latest development unstable. 
https://github.com/endeavouros-team/EndeavourOS-ISO#build
Calamares versions used for main unstable are not at the default repo.

**Comment by dalto8** [comment]
To build the ISO off the tag, you will need to modify packages.x86_64 and remove `ipw2200-fw` and `ipw2100-fw`

**Comment by killajoe** [comment]
this too ;)

**Comment by dalto8** [comment]
Using the ISO built off 22.09, try downgrading the config packages to the latest rev of 22.09.2.3.

**Comment by dalto8** [comment]
> Thank you,I am building tag 22.9 now,is there any way to build a working iso of main branch?

It is possible, you would need to switch to calamares-git and build your own versions of all the calamares packages.

However, even if you did all that, we are currently in the middle of development cycle so you would get an ISO that isn't fully working.

You are better off building off the tag.
