### ISSUE TITLE
"enhancement" Changing Nano to Micro, as the simple cli text editor

### ISSUE THREAD

**Issue by Vilianexe** [endeavouros-team/EndeavourOS-ISO#41]
[Micro](https://github.com/zyedidia/micro) a more powerful and modern alternative to Nano, with more intuitive keybinds, cursor support, unlimited undo/redo and is well maintained, couldn't it be a good replacement for nano?

(sorry if I am asking in the wrong place, i I couldn't find another place to post)

**Comment by killajoe** [comment]
nano is also [well-maintained](https://git.savannah.gnu.org/cgit/nano.git/log/) and minimal i do not see any downside on nano and nothing that would put micro over nano. 
And it is easy to install micro if it fits your needs better. 
You can also remove nano from packages list and add micro as user_pkglist on install process.
