### ISSUE TITLE
Optimus Nvidia Systems are Broken due to Missing Kernel Parameter 

### ISSUE THREAD

**Issue by TheKarion** [endeavouros-team/EndeavourOS-ISO#42]
Yesterday I had to reinstall my system 6 times, and this is one issue that was persistent that i didnt realize till the 6th install. The required kernel parameter "nvidia_drm.modeset=1" Without this, my display would cause a lot of animation glitches on kde and make games either crash on load or run at 60hz despite my display reading 144hz. I've never had this issue before, maybe it got changed when nvidia-inst got messed up a few weeks ago?

**Comment by killajoe** [comment]
Again same as mentioned in the other report, this is the wrong place for issues with installing the system.
And no info or details are provided to investigate the issue.
