### ISSUE TITLE
KDE Edition Still Broken on Install

### ISSUE THREAD

**Issue by TheKarion** [endeavouros-team/EndeavourOS-ISO#43]
I had this same issue when I tried to install just kde edition 3 months ago, all icons are missing and the right click menu spans the entire screen, as well as animations are broken. I was able to fix it by installing cinnamon, and kde without eos-plasma-settings and eos-sddm-settings. When I had this issue 3 months ago I fixed it by installing Qtile edition and installing plasma myself. Sadly I don't have any screenshots as they got deleted when I reinstalled my system, but I've had people in the discord recreate it.

**Comment by killajoe** [comment]
thanks for the info.. but without any log or details about how the system was installed or the hardware in use we can not do much..also this is not an issue with the ISO, is the ISO is only providing the live session where the installer runs.

Your Fixes are also no fixes for the issue you describe with kde.

I would be lucky to investigate the issue if you will provide needed info or a link to the reddit thread at least so I can do some research.

**Comment by TheKarion** [comment]
Wheres the correct place to put the issue? Also how would I get a log? Just run it in a virtual machine to replicate it?

**Comment by dalto8** [comment]
The forum would be the best place for an issue like this one.  @killajoe linked it above.

Yes, you would need to replicate to get it a log.  The install logs are placed in `/var/log` of the installed system after the install completes.

It would also help to see some screenshots of what you are referring to.  KDE is one of the most common DEs to install and I haven't seen this issue reported yet.  It is also the version I personally use for most of my testing.

**Comment by killajoe** [comment]
hmm, i give the links for proper places for reporting already. 
And installer logs are available on the livesession also if install failed:
`~/endeavour-install.log`
on installed system you will find a safed copy under:
`/var/log/endeavour-install.log`
But this issue here is closed for good now ;)
