### ISSUE TITLE
`ipconfig not found`

### ISSUE THREAD

**Issue by beta-tester** [endeavouros-team/EndeavourOS-ISO#46]
hi,
 i just tried to add `Endeavouros_Cassini_Nova-03-2023_R1.iso` to my https://github.com/beta-tester/RPi-PXE-Server project.
but every time i try to PXE boot my PC into EndeavourOS i get the error message:
```log
/init: line ...: ipconfig: not found
ERROR: failed to configure Network
...
```
on the root prompt i tried to fix the problem manually but indeed `ipconfig` seems not installed on the ISO during PXE boot.

here the PXE boot options i used:
```config
LABEL endeavour-x64
    MENU LABEL EndeavourOS
    KERNEL http://192.168.1.1/srv/nfs/endeavour-x64/arch/boot/x86_64/vmlinuz-linux
    INITRD http://192.168.1.1/srv/nfs/endeavour-x64/arch/boot/intel-ucode.img,http://192.168.1.1/srv/nfs/endeavour-x64/arch/boot/amd-ucode.img,http://192.168.1.1/srv/nfs/endeavour-x64/arch/boot/x86_64/initramfs-linux.img
    APPEND ip=dhcp ro archisobasedir=arch archiso_nfs_srv=192.168.1.1:/srv/nfs/endeavour-x64 copytoram=n
    SYSAPPEND 3
    TEXT HELP
        Boot to EndeavourOS Linux
    ENDTEXT
```

**Comment by dalto8** [comment]
The current ISO does not support PXE boot.

It doesn't include the `mkinitcpio-nfs-utils` which, for some reason, is required for PXE boot.

**Comment by beta-tester** [comment]
i fond this thread: https://forum.endeavouros.com/t/cassini-22-12-archiso-pxe-common-hook-fails-to-configure-network/37029
looks like the package `mkinitcpio-nfs-utils` was included in earlier versions of endeavouros.

- can i download older ISOs where that package is still included?
- does it makes problems to include that package again to the next endeavouros ISO release?

**Comment by beta-tester** [comment]
@dalto8 , i have one more question:

> The current ISO does not support PXE boot.

when i boot `Endeavouros_Cassini_Nova-03-2023_R1.iso` from an USB stick, i see on screen the following output:
```sh
...
Starting version 251.2-1-arch
:: running early hook [archiso_pxe_nbd]
:: eunning hook [udev]
:: Triggering uevents...
:: running hook [memdifk]
:: running hook [archiso]
:: running hook [archiso_loop_mnt]
:: running hook [archiso_pxe_common]
:: running hook [archiso_pxe_nbd]
:: running hook [archiso_pxe_http]
:: running hook [archiso_pxe_nfs]
...
:: running late hook [archiso_pxe_common]
...
Welcome to EndeavourOS!
```
to me it looks like there is a lot of PXE stuff going on there.
why i see all these PXE stuff when PXE is not supported?

**Comment by dalto8** [comment]
> why i see all these PXE stuff when PXE is not supported?

To be clear, our goal was not to remove PXE support.  We removed the package `mkinitcpio-nfs-utils` in a general package cleanup.

However, since PXE booting is not common for us, in future releases we will need to decide if we want to support it going forward or not.

**Comment by beta-tester** [comment]
is a pity for me, but I have to accept this decision.
so what I see there are only the residues of an incomplete cleaning.

thank you for your time to clarify.
