### ISSUE TITLE
black screen when having a second monitor

### ISSUE THREAD

**Issue by yahya-mohammed07** [endeavouros-team/EndeavourOS-ISO#50]
Hi, sometimes when i run the system the second screen just gets black and nothing is clickable except with the Icons-only TaskManager, every time this happens i switch primary screens and things go ok.

I hope you resolve this, it's minor but sometimes annoying.

**Comment by dalto8** [comment]
For troubleshooting problems like this, it is better to use the forum at https://forum.endeavouros.com.

There are many people who read that site and help troubleshoot issues like this.

**Comment by killajoe** [comment]
or of it fits you better use telegram chat: https://t.me/Endeavouros
