### ISSUE TITLE
Fresh install - Brave and Chromium cant download files

### ISSUE THREAD

**Issue by dford16** [endeavouros-team/EndeavourOS-ISO#51]
https://forum.endeavouros.com/t/fresh-install-brave-and-chromium-cant-download-files/46015

https://aur.archlinux.org/packages/brave-bin

https://www.youtube.com/watch?v=0S-VKAHUNWw

http://ix.io/4HxY

Either this is a upstream chromium issue or an endeavour OS issue, I only find users on endeavour OS who have this problem so far.

**Comment by killajoe** [comment]
This is only for quesztions/issues regarding to ISO development the right place to post BUGS is here:
https://forum.endeavouros.com/c/arch-based-related-questions/bug-reports/64
