### ISSUE TITLE
[Feature Request] Enable GeckoLinux font rendering config files by default for smoother font rendering

### ISSUE THREAD

**Issue by amethylghostling** [endeavouros-team/EndeavourOS-ISO#53]
This [forum post](https://github.com/geckolinux/geckolinux-project/discussions/475) explains how to apply them.

**Comparison in KDE ( 1 QT based apps)**
![Uploading image.png…](Before in openSUSE)
Before
![Uploading image.png…](After in openSUSE/GeckoLinux)
After

**Comparison in XFCE (All GTK based apps)**
![Uploading image.png…](Before in openSUSE)
Before
![Uploading image.png…](After in openSUSE/GeckoLinux)
After

**Comparison in Dolphin with same theme in KDE**
![Uploading EndeavourOS.png…](Before in EndeavourOS)
Before
![Uploading GeckoLinux.png…](After)
After

**Some Remarks**
On my monitor, there is a big difference. The text is thicker and smoother. Better font rendering would reduce eye strain for users and make reading text in eos easier for people with vision impairments such as myself (although mine is not permanent, it is a problem of focus on vision). I don't think the difference at least on my monitor be excused for a different GTK theme.

**Comment by dalto8** [comment]
Your image links aren't working.  It looks like they didn't finish uploading.

That being said, font rendering is very much a personal preference.  It depends what you are used to.  Many users prefer accurate font rendering.  Others prefer a more aliased look. 

No matter which we choose, a group of users will be unsatisfied.  In general, we try to use the defaults and let each individual customize it to their own preferences.

**Comment by amethylghostling** [comment]
> That being said, font rendering is very much a personal preference. It depends what you are used to. Many users prefer accurate font rendering. Others prefer a more aliased look.
> 
> No matter which we choose, a group of users will be unsatisfied. In general, we try to use the defaults and let each individual customize it to their own preferences.

I think if you guys use the GeckoLinux font rendering config files EOS would become more appealing to new to Linux ()

**Comment by amethylghostling** [comment]
This [page](https://github.com/geckolinux/geckolinux-project/issues/131) has the screenshots that I was uploading here

**Comment by amethylghostling** [comment]
> Your image links aren't working. It looks like they didn't finish uploading.
This [page](https://github.com/geckolinux/geckolinux-project/issues/131) has the screenshots that I was uploading here

**Comment by killajoe** [comment]
> On my monitor, there is a big difference.

and depending on hardware it will be different.. i do already see this on one system using two different displays both almost the same specs and hardware. 
Also i can confess i am  into the font rendering thing for a long time myself .. i do not see that it will be something easy to maintain and implement, better is to provide a tutorial anyone interested can use to try out themself.

**Comment by amethylghostling** [comment]
> .. i do not see that it will be something easy to maintain and implement, better is to provide a tutorial anyone interested can use to try out themself.

At least in GeckoLinux (openSUSE Tumbleweed) in which the config files are enabled out of the box, you don't need to maintain anything. The config files keep working with every update.

**Comment by amethylghostling** [comment]
> better is to provide a tutorial anyone interested can use to try out themself.
If you are not gonna include it ootb, then please make an article on how to apply it.

**Comment by amethylghostling** [comment]
> > On my monitor, there is a big difference.
> 
> and depending on hardware it will be different.. i do already see this on one system using two different displays both almost the same specs and hardware. Also i can confess i am into the font rendering thing for a long time myself .. i do not see that it will be something easy to maintain and implement, better is to provide a tutorial anyone interested can use to try out themself.

Better yet make a package that can be selected during online install that enables these config files

**Comment by dalto8** [comment]
Many of our tutorials or articles are developed by the community.  If you have an interest in this it would be great if you could write a tutorial on it to share with the rest of the community.

**Comment by amethylghostling** [comment]
I don't think that my english is good enough to be able to do a good job at writing this tutorial due to my mental illnesses and problems.

**Comment by amethylghostling** [comment]
> Many of our tutorials or articles are developed by the community. If you have an interest in this it would be great if you could write a tutorial on it to share with the rest of the community.

I don't think that my english is good enough to be able to do a good job at writing this tutorial due to my mental illnesses and problems.
