### ISSUE TITLE
Using live USB no mirrors found

### ISSUE THREAD

**Issue by dewaltz** [endeavouros-team/EndeavourOS-ISO#57]
HI,

I have looped around for a few hours. No idea Why mirrors lists are all broken. i tried updated before install no mirors found. connected to wifi and eth, ping test passed firefox browser working and surfing but have formatted my drive 20 times trying to install with same error about mirrorlist any ideas?

**Comment by killajoe** [comment]
same for me.. it only adds maximum 2 mirrors in some cases.. 
But go to forum this here is for development questions not general user request/bug reports
https://forum.endeavouros.com/t/reflector-simple-not-working/50162/5

**Comment by dewaltz** [comment]
This is a big blocker for me. Using endervourOS to avoid setup, now i need to debug setup. wood be quickier going back to arch at this point. S frustrated even tempted to go  to windows. never had an issue installing in 20years. this is bugging as its simple and stupid bug.

**Comment by killajoe** [comment]
> wood be quickier going back to arch at this point.

would be the same on arch rankmirror scripts are somehow broken. 
You can add custom morrporlist into /etc/pacman.d/mirrorlist  on the livesession this will be used to install thats not hard to do.. go to https://archlinux.org/mirrorlist/ create a list replace `#S` with `S`  using Kate and replace the mirrorlist with it `sudo cp mirrorlist /etc/pacman.d/mirrorlist` But feel free tpo do what ever you have to aside from blaming üpeople offering a free OS by free will in their free time ;)  W edo simply habve no solution to the issue nor do we develop the used toosl themself..

**Comment by dalto8** [comment]
It isn't an issue with the tools, it is an issue with mirror status.  You can see if you look at the [Arch mirror status page](https://archlinux.org/mirrors/status/).

All of the mirrors are out of sync.  Since the tools check for mirror sync completion, they aren't returning any mirrors.
