### ISSUE TITLE
KDE (Dolphin) video thumbnails don't work on default install

### ISSUE THREAD

**Issue by markmuir87** [endeavouros-team/EndeavourOS-ISO#58]
A very small issue, perhaps something that could be addressed in your next release.

**Issue**: After installing EndeavourOS_Galileo-Neo-2024.01.25 with KDE selected as the DE, video preview thumbnails do not work because extra/ffmpegthumbs is not installed by default. They start working after installing ffmpegthumbs with pacman.

**Suggested fix**: If the user selects KDE during install, install ffmpegthumbs by default.

I hope this is the right place to raise this issue. Thanks for the fantastic distro!

**Comment by killajoe** [comment]
Seems legit.. we have ffmpegthumbnailer installed, seems not the one to be used on dolphin.. 
Partly this is the correct place, for iso live session and offline installs, online uses this list:

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/EndeavourOS-ISO/commit/eed99f30258cc751ec9848cc912215ec62253ade
resolves it for ISO and offline ... and this:
https://github.com/endeavouros-team/calamares/commit/a1981b30adfa5e3bb29b4a1bda63539c1ac56551
for online. 

We may hotfix it in to get applied to current release.
