### ISSUE TITLE
Fail to start the "Linux Boot manager"

### ISSUE THREAD

**Issue by T1z3n** [endeavouros-team/EndeavourOS-ISO#61]
Currently the BIOS doesn´t start the "Linux Boot manager" automatically.

My current workaround is to chosse the "Linux Boot manager" via F11 in the UEFI manually.

---Set-up---
Operating System: EndeavourOS 
KDE Plasma Version: 6.0.1
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.2
Kernel Version: 6.7.9-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5500
Memory: 31.2 GiB of RAM
Graphics Processor: AMD Radeon RX 6600
---

**Comment by dalto8** [comment]
System support issues like this are better solved at the forum: https://forum.endeavouros.com
