### ISSUE TITLE
Konsole theme gone after offline install (Plasma)

### ISSUE THREAD

**Issue by wilyJ80** [endeavouros-team/EndeavourOS-ISO#62]
Description: after the offline installation, all theming in the default offline environment (KDE Plasma) persists, except for that beautiful Konsole theme. 

Can you fix this? I wonder what is the cause for that. I had to dig around to find the Konsole theme.

**Comment by killajoe** [comment]
I just was thinking about the same after installing on my new notebook ;)  
I was only setting this theme on Konsole for the live session to keep the theme from before, installed system do not apply Konsole setup.

We do only set very minimal fixes for installed systems aside from i3 and xfce4 (xfce4 was the live before) 

I will try to create a theme package for Konsole so we can keep it optional. 

But you can steal the setup from the ISO repo here:

`~/.config/konsolerc`

https://github.com/endeavouros-team/EndeavourOS-ISO/blob/main/airootfs/root/endeavouros-skel-liveuser/src/etc/skel/.config/konsolerc

`~/.local/share/konsole`

https://github.com/endeavouros-team/EndeavourOS-ISO/tree/main/airootfs/root/endeavouros-skel-liveuser/src/etc/skel/.local/share/konsole
