### ISSUE TITLE
Are the EndeavourOS applications required?

### ISSUE THREAD

**Issue by binarykitchen** [endeavouros-team/EndeavourOS-ISO#63]
Hello all,

Thanks for the neat installer, well done.

I wonder what the EndeavourOS applications are for? In the installer, they come without a description. But all the other features have a description.

I'm after an absolute minimal installation and wonder if things would break without these? First time I installed without them, I saw errors in the logs,  so I tried a second time with them and then it worked.

A bit confusing, misleading. Would be good to explain.

Thanks heaps :)

**Comment by dalto8** [comment]
You should be able to install without the EndeavourOS applications but there is a bug in the current installer.  It has already been fixed and when the next ISO is released it will no longer be required.

In the meantime, if you choose only `eos-log-tool` that will be enough to make the install succeed and you can remove it after installation.

**Comment by binarykitchen** [comment]
Great thanks mateOn 25 Jun 2024, at 13:53, dalto8 ***@***.***> wrote:﻿
You should be able to install without the EndeavourOS applications but there is a bug in the current installer.  It has already been fixed and when the next ISO is released it will no longer be required.
In the meantime, if you choose only eos-log-tool that will be enough to make the install succeed and you can remove it after installation.
