### ISSUE TITLE
Implement auto detection of CPU

### ISSUE THREAD

**Issue by binarykitchen** [endeavouros-team/EndeavourOS-ISO#64]
It's me again. And again, compliments for the cool installer.

Another suggestion. When I'm on an Intel CPU and come with an old Intel GPU, then I would not autoselect those features:
- amd-ucode
- xf86-video-amdgpu

And so on. How about implementing auto detection and auto selection? In my case, xf86-video-intel is missing.

Thoughts?

**Comment by dalto8** [comment]
Even if those are selected, they should get removed at the end of the install if you don't have any hardware that needs them.

`xf86-video-intel` should also get installed if you need it but in most cases, it is better to use the modesetting driver instead so we would not install it in those cases.

What specific CPU are you using?

**Comment by binarykitchen** [comment]
Intel core i7

Ok noted, you say they still get installed. Would be good to mention this somewhere during setup. A bit misleading. More transparency would be good. Thanks :)

**Comment by dalto8** [comment]
> Intel core i7

Which CPU, specifically?  There are at least 30 different CPUs with core i7 branding.

**Comment by binarykitchen** [comment]
Sorry. CPU model of my laptop is:

Inter(R) Core(TM) i7-10510U CPU @ 1.80 GHz

**Comment by dalto8** [comment]
OK, yes.  That model should definitely not get `xf86-video-intel` so that is the correct behavior.

**Comment by binarykitchen** [comment]
@dalto8 Cool. Then nothing is wrong and can close this ticket - yet, I'd suggest improving descriptions to make this somewhat clear for us users :)
