### ISSUE TITLE
Virtual console service errors during boot

### ISSUE THREAD

**Issue by binarykitchen** [endeavouros-team/EndeavourOS-ISO#65]
The following happens right after a fresh installation for New Zealand locale:
```
Jun 26 09:32:03 M1 systemd[1]: systemd-vconsole-setup.service: Main process exited, code=exited, status=1/FAILURE
Jun 26 09:32:03 M1 systemd[1]: systemd-vconsole-setup.service: Failed with result 'exit-code'.
Jun 26 09:32:03 M1 systemd[1]: run-credentials-systemd\x2dvconsole\x2dsetup.service.mount: Deactivated successfully.
Jun 26 09:32:03 M1 systemd-vconsole-setup[164]: /usr/bin/loadkeys failed with exit status 1.
Jun 26 09:32:03 M1 systemd-vconsole-setup[171]: loadkeys: Unable to open file: nz: No such file or directory
Jun 26 09:32:03 M1 systemd-vconsole-setup[457]: loadkeys: Unable to open file: nz: No such file or directory
Jun 26 09:32:03 M1 systemd-vconsole-setup[451]: /usr/bin/loadkeys failed with exit status 1.
```
![24-06-25 21-31-45 4242](https://github.com/endeavouros-team/EndeavourOS-ISO/assets/177641/91887f78-b008-4461-aa1e-1ccb1a2486d6)

**Comment by killajoe** [comment]
This is not related to the ISO more related to calamares installer.
And if possible went to the Forum to report installation Bugs:
https://forum.endeavouros.com/c/general-system/endeavouros-installation/64
Or at least report at the correct repository:
https://github.com/endeavouros-team/calamares

**Comment by binarykitchen** [comment]
Thanks, @killajoe, I wasn't sure where to report. I'll take care of it.
