### ISSUE TITLE
Crash installtion when create Volume Group

### ISSUE THREAD

**Issue by mahdiyar11007** [endeavouros-team/EndeavourOS-ISO#66]
Hi,
I want to do the installation when partitioning the hard disk, create a partition with type lvm-pv and click on create Volume Group and check this lvm-pv partition, crashed installation process.

**Comment by killajoe** [comment]
This seems not be related with the Boot medium ISO Framework, that's most likely an issue with the installer itself:
https://github.com/endeavouros-team/calamares
Best place to report install issues is the Forum:
https://forum.endeavouros.com/c/general-system/endeavouros-installation/64

**Comment by killajoe** [comment]
> create a partition with type lvm-pv and click on create Volume Group and check this lvm-pv partition, crashed installation process.

LVM part of the manual partition Module is broken upstream for a long time also. And a candidate for removal.
