### ISSUE TITLE
Wifi

### ISSUE THREAD

**Issue by wmrose** [endeavouros-team/EndeavourOS-ISO#67]
Could not get my wifi to work until I edited NetworkManager.conf to force it to use IWD per Prohoster.info's blog.

[device]
wifi.backend=iwd

Is all it took.  Recommend adding it to the package as a default.

Thank you for the great work!

**Comment by killajoe** [comment]
we are talking about the LiveSession or installed system here?

**Comment by killajoe** [comment]
Close as of no reaction

**Comment by wmrose** [comment]
Installed system.  Using nmcli it showed memory allocation problems and
constant 'wifi connected, connection lost' notifications.  Live system also
dead of course.  Locked to IWD it has been working perfectly.
Thank you!
