### ISSUE TITLE
2024.06.25 ISO: Broken Image (missing libraries)

### ISSUE THREAD

**Issue by cookiengineer** [endeavouros-team/EndeavourOS-ISO#68]
Hey there,

I wanted to try out EndeavourOS today for my old Intel NUC machine, but it isn't booting and drops back to a root shell after a bunch of processes failed. The hardware setup is pretty standard, Intel NUC 4th gen and an m2 SSD connected to it, nothing more other than my USB keyboard and HDMI screen.

Missing libraries seem to be:

- `libmount.so.1`
- `libsystemd-shared-256.1-1.so`
- `libzstd.so.1` (which leads to initramfs unpacking to fail)

Here's the photo of the bootup process. The terminal isn't reacting to USB devices, because udev (modprobe to load the kernel module/s) failed beforehand. Otherwise I would've tried to submit more details on which libraries are linked to which folders, like  an `ldd` output or something :-/

![photo_2024-09-26_07-14-01](https://github.com/user-attachments/assets/902bcc9a-b66d-4662-84f0-751f971c348d)

**Comment by killajoe** [comment]
This is not the ISO file missing something its may corrupted ISO file or bad media.
Could be also secure boot is not set to off in firmware of the Hardware. 
![Screenshot_20240927_221254](https://github.com/user-attachments/assets/654b2bdf-796b-4439-b238-d408f9cf732f)
With this the image you are using is may corrupted check it with the sha512sum. 
In case issue is still present feel free to ask about at the telegram chat or forum:
https://forum.endeavouros.com/ https://t.me/Endeavouros
