### ISSUE TITLE
Endeavouros black screen fix

### ISSUE THREAD

**Issue by inSade-prog** [endeavouros-team/EndeavourOS-ISO#69]
Hi, I am a windows user … so now I have decided to switch to Linux because my PC doesn’t meet the minimum requirements for windows 11 so watched few videos and created a bootable USB drive and
now I am stuck on black screen…

I don’t know sh*t about Linux sO please help me fix this issue. I am like a new born :sob:

Initially it runs fine… When it comes to that GUI thing where you install actual os (I meant to say GUI installation window) it just doesn’t show :confused:… it’s a full black screen

My PC specs:
HP elite desk 705 g1

Processor: AMD A8 PRO-7600B (Base 3.1 GHz / Turbo Core 3.8 GHz

GPU: Nvidia GTX 750 ti

also if this helps: AMD Radeon R7 Graphics (384 Stream Processor)

Motherboard: AMD A88X Chipset-based

Memory: 12gb

**Comment by manuel-192** [comment]
Please go to `https://forum.endeavouros.com` to get quick help.
