### ISSUE TITLE
Live wallpaper  (possibly) has wrong release in files

### ISSUE THREAD

**Issue by Pandademic** [endeavouros-team/EndeavourOS-ISO#7]
Shouldn't it be Atlantis neo , not Atlantis ?

**Comment by killajoe** [comment]
it is still Atlantis ;) the wallpaper is changed on building ISO and the one in the repo is only a placeholder.

**Comment by Pandademic** [comment]
OK , thanks !

**Comment by killajoe** [comment]
i change it anyway so it will not cause confusion ;)
https://github.com/endeavouros-team/EndeavourOS-ISO/commit/80b20cb0e1e57b1a23976bcac92372b3c776a356

**Comment by Pandademic** [comment]
Thanks!
